baseURL: "https://shtakasu.github.io/"
title: "Shotaro Takasu's Website "
pagination:
  pagerSize: 5
theme: "PaperMod"
publishDir: "docs"
#canonifyurls: true

#enableRobotsTXT: true
#buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "G-DR5J4VSCPF"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Shotaro Takasu
  description: "Shotaro Takasu's Website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Shotaro Takasu
  # author: ["Me", "You"] # multiple authors
  images: ["myimage.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Shotaro Takasu's Website"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Shotaro Takasu, MD, PhD（高須 正太郎）
    subtitle: "Dynamical Systems, Statistical Physics, Theoretical Neuroscience, and Neuropsychiatry"

    imageUrl: "myimage.jpg"
    imageWidth: 120
    imageHeight: 150
    #imageTitle: my image
    buttons:
      - name: Profile
        url: profile
      - name: Research
        url: research
      - name: Contact
        url: contact

  # home-info mode
  #homeInfoParams:
  #  Title: "Shotaro Takasu"
  #  Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ShotaroTakasu"
    - name: github
      url: "https://github.com/shtakasu"

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
 
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Profile
      name: Profile
      url: /profile/
      weight: 1
    - identifier: Research
      name: Research
      url: /research/
      weight: 2
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 3
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai